platform :ios, '13.4'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

target 'VeriffSdk' do
  # Pods for VeriffSdk
  pod 'VeriffSDK', '7.6.0'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )
end
